apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexusstorage
spec:
  storageClassName: nexusstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ .Values.pv.nexusstorage }}
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.nexuspvc }}
spec:
  storageClassName: nexusstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.nexusstoragesize }}    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsstorage
spec:
  storageClassName: jenkinsstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ .Values.pv.jenkinsstorage }}
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.jenkinspvc }}
spec:
  storageClassName: jenkinsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.jenkinsstoragesize }}   

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarstorage
spec:
  storageClassName: sonarstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.sonarstoragesize }}   
  hostPath:
    path: {{ .Values.pv.sonarstorage }}/data
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.sonarpvc }}
spec:
  storageClassName: sonarstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.sonarstoragesize }}    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarlogsstorage
spec:
  storageClassName: sonarlogsstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.sonarstoragesize }}   
  hostPath:
    path: {{ .Values.pv.sonarstorage }}/logs
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.sonarlogspvc }}
spec:
  storageClassName: sonarlogsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.sonarstoragesize }}    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarextstorage
spec:
  storageClassName: sonarextstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.sonarstoragesize }}   
  hostPath:
    path: {{ .Values.pv.sonarstorage }}/ext
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.sonarextpvc }}
spec:
  storageClassName: sonarextstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.sonarstoragesize }}             