apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexusstorage
spec:
  storageClassName: nexusstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ .Values.pv.nexusstorage }}
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.nexuspvc }}
spec:
  storageClassName: nexusstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.nexusstoragesize }}    

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsstorage
spec:
  storageClassName: jenkinsstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ .Values.pv.jenkinsstorage }}
    type: DirectoryOrCreate 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.jenkinspvc }}
spec:
  storageClassName: jenkinsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.jenkinsstoragesize }}   
          